version: "3.9"

services:
  web:
    build: .
    container_name: mini_lms_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: mini_lms_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mini_lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
