"""add teacher_id to course

Revision ID: 1a95e1cd06b0
Revises: 
Create Date: 2026-03-31 15:44:15.073103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a95e1cd06b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('course_name'))
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('course_name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('course_name'), ['course_name'], unique=True)
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
